tag-prefix = "block-explorers-"
pre-release-commit-message = "chore: release block-explorers {{version}}"
allow-branch = ["main"]
sign-commit = true
sign-tag = true
rate-limit.existing-packages = 10
pre-release-hook = ["bash", "-c", "$WORKSPACE_ROOT/.github/scripts/changelog.sh --tag {{version}}"]
